apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "usersapi.fullname" . }}-clusterrolebinding
  labels:
    app: visualoffice
    component: usersapi
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ template "usersapi.fullname" . }}-default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "usersapi.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io