---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "usersapi.fullname" . }}
  labels:
    app: visualoffice
    component: usersapi
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualoffice
      component: usersapi
      release: {{ .Release.Name }}
  template:
    metadata:
      name: usersapi-pod
      labels:
        app: visualoffice
        component: usersapi
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: usersapi
        env:
        - name: MYSQL_SERVER_NAME
          value: {{ .Values.databaseHost | default (printf "%s-mysql" .Release.Name)}} #mysql
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MYSQL_USER
        - name: MYSQL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MYSQL_USER_PASSWORD        
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MYSQL_DATABASE 