---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "usersapi.fullname" . }}
  labels:
    app: visualoffice
    component: usersapi
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.externalPort}}
    targetPort: {{ .Values.service.internalPort}}
  selector:
    app: visualoffice
    component: usersapi
    release: {{ .Release.Name }}