---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "webappsite.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: letsencrypt-staging
  rules:
  - host: {{ .Values.ingress.host | default .Release.Name }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "webappsite.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}