---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "webappsite.fullname" . }}
  labels:
    app: visualoffice
    component: webappsite
    release: {{ .Release.Name}}
spec:
  type: NodePort
  ports:  
  - port: {{ .Values.service.internalPort}}
    protocol: TCP
    targetPort: {{ .Values.service.externalPort}}
  selector:
    app: visualoffice
    component: webappsite
    release: {{ .Release.Name}}