{
 "title": "Visualoffice Application",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=\"visualoffice\"}[2m]))"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(dotnet_total_memory_bytes)" }
   ]
  },
  {
   "title": "Average CPU Usage, by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=~\"visualoffice\"}[2m])"
    }
   ]
  },
  {
   "title": "Memory usage, by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dotnet_total_memory_bytes" }
   ]
  },
  {
   "title": "Average request execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum[1m]) / rate(request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Average number of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    { "expr": "rate(total_requests[2m])" }
   ]
  },
  {
   "title": "Average request quantile 95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket[2m])) by (le))"
    }
   ]
  }
 ]
}