image: alpine:latest

stages:
  - test
  - staging
  - production


test_charts:
  stage: test
  only:
    refs:
      - master
      - triggers
  before_script:
    - apk add openssl curl tar 
    - curl https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz | tar zx
    - mv linux-amd64/helm /usr/bin/
    - helm version --client
  script:
    - helm lint mysql
    - helm lint usersapi
    - helm lint visualoffice
    - helm lint webappsite

.base_deploy:
  variables:
    name: $CI_ENVIRONMENT_SLUG
  only:
    refs:
      - master
  before_script:
    - apk add -U openssl curl tar gzip bash ca-certificates git
    - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
    - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk
    - apk add glibc-2.23-r3.apk
    - curl https://storage.googleapis.com/pub/gsutil.tar.gz | tar -xz -C $HOME
    - export PATH=${PATH}:$HOME/gsutil
    - curl https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz | tar zx
    - mv linux-amd64/helm /usr/bin/
    - helm version --client
    - curl  -o /usr/bin/sync-repo.sh https://raw.githubusercontent.com/kubernetes/helm/master/scripts/sync-repo.sh
    - chmod a+x /usr/bin/sync-repo.sh
    - curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x /usr/bin/kubectl
    - kubectl version --client
    - kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
  script:
    - helm dep build visualoffice
    - >
      echo helm upgrade \
        --install \
        --wait \
        --set webappsite.ingress.host="$host" \
        --set usersapi.image.tag=latest \
        --set webappsite.image.tag=latest \
        --set mysql.image.tag=latest \
        --namespace="$KUBE_NAMESPACE" \
        --version="$CI_PIPELINE_ID-$CI_JOB_ID" \
        "$name" \
        visualoffice
    - >
      helm upgrade \
        --install \
        --wait \
        --set webappsite.ingress.host="$host" \
        --set usersapi.image.tag=latest \
        --set webappsite.image.tag=latest \
        --set mysql.image.tag=latest \
        --namespace="$KUBE_NAMESPACE" \
        --version="$CI_PIPELINE_ID-$CI_JOB_ID" \
        "$name" \
        visualoffice

staging:
  extends: .base_deploy
  stage: staging
  variables:
    KUBE_NAMESPACE: staging
    host: staging.$URL
  environment:
    name: staging
    url: http://staging.$URL

production:
  extends: .base_deploy
  stage: production
  variables:
    KUBE_NAMESPACE: production
    host: production.$URL
  environment:
    name: production
    url: http://production.$URL
  when: manual