apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "mysql.fullname" . }}-clusterrole
  labels:
    app: visualoffice
    component: mysql
    release: {{ .Release.Name}}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]