---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app: visualoffice
    component: mysql
    release: {{ .Release.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualoffice
      component: mysql
      release: {{ .Release.Name}}
  template:
    metadata:
      name: mysql
      labels:
        app: visualoffice
        component: mysql
        release: {{ .Release.Name}}
    spec:
      containers:
      - image: {{ template "image.fullname" . }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ template "mysql.fullname" . }}-pvc