{{- if .Release.IsInstall }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mysql.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageValue | default "2Gi"}}
  storageClassName: {{ template "mysql.datastore" . }}
{{- end }}