{{- if .Release.IsInstall }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name}}-pvc #mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageValue | default "2Gi"}}
  storageClassName: {{ .Values.storageClassName | default (printf "%s-ssd" .Chart.Name)}}
{{- end }}