---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app: visualoffice
    component: mysql
    release: {{ .Release.Name}}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: visualoffice
    component: mysql
    release: {{ .Release.Name}}