{{- if .Release.IsInstall }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: {{ template "mysql.datastore" . }}
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: {{ .Values.storageClass | default "pd-ssd" }}
{{- end }}